name: shared nodejs build #Name of the workflow
on: # type of event to trigger workflow
  workflow_call:  #this workflow is called by application workflow
    inputs:  # Caller should supply below inputs
      project: 
        type: string
        required: true
      component:
        type: string
        required: true
      description:
        type: string
        required: false
        default: ""

env:
  acc_id: 406682759639


jobs:
  nodejs:  # name of the job
    runs-on: nodejs  #the workflow runs on nodejs runner
    permissions:  # Controls what GITHUB token allowed to do for the job
     contents: read
     statuses: write
    steps:
    - name: Get code  #git clone the current repo
      uses: actions/checkout@v7

    # $GITHUB_ENV: commit id available to subsequent steps in same job
    # $GUTHUB_OUTPUT: Commit id available in all jobs.
    - name: Get app version
      run: |
        echo "appVersion=${GITHUB_SHA::9}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      id: unit_tests
      run: echo "Unit test successful"

    - name: Update unit test status
      if: always()
      uses: nihu-ci/usable-workflow/.github/actions@main
      with:
        context: UNIT_TESTS
        sha: ${{ github.sha }}
        description: "Unit test ${{ steps.unit_tests.outcome }}"
        state: ${{ steps.unit_tests.outcome }}

    - name: Scan dependencies
      id: depenency_check
      run: echo "dependency scan successful"
    
    - name: Update dependencies test status
      uses: nihu-ci/usable-workflow/.github/actions@main
      with:
        context: DEPENDENCY_CHECK
        sha: ${{ github.sha }}
        description: "Unit test ${{ steps.depenency_check.outcome }}"
        state: ${{ steps.depenency_check.outcome }}
      
    - name: Build image
      id: build_status
      run: |
        docker build -t ${acc_id}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:$appVersion .
        docker images

    - name: Update build status
      uses: nihu-ci/usable-workflow/.github/actions@main
      with:
        context: BUILD_STATUS
        sha: ${{ github.sha }}
        description: "Unit test ${{ steps.build_status.outcome }}"
        state: ${{ steps.build_status.outcome }}
      