name: shared nodejs build #Name of the workflow
on: # type of event to trigger workflow
  workflow_call:  #this workflow is called by application workflow
    inputs:  # Caller should supply below inputs
      project: 
        type: string
        required: true
      component:
        type: string
        required: true
      description:
        type: string
        required: false
        default: ""

env:
  acc_id: 406682759639


jobs:
  nodejs:  # name of the job
    runs-on: nodejs  #the workflow runs on nodejs runner
    permissions:  # Controls what GITHUB token allowed to do for the job
     contents: read
     statuses: write
    steps:
    - name: Get code  #git clone the current repo
      uses: actions/checkout@v7

    # $GITHUB_ENV: commit id available to subsequent steps in same job
    # $GUTHUB_OUTPUT: Commit id available in all jobs.
    - name: Get app version
      run: |
        echo "appVersion=${GITHUB_SHA::9}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      id: unit_tests
      run: echo "Unit test successful"

    - name: Update unit test status
      if: always()
      uses: nihu-ci/usable-workflow/.github/actions@main
      with:
        context: UNIT_TESTS
        sha: ${{ github.sha }}
        description: ${{ steps.unit_tests.outcome }}
        state: ${{ steps.unit_tests.outcome }}

    - name: Build image
      id: build_status
      run: |
        docker build -t ${acc_id}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:$appVersion .
        docker images

    - name: Update build status
      uses: nihu-ci/usable-workflow/.github/actions@main
      with:
        context: DOCKER_BUILD
        sha: ${{ github.sha }}
        description: ${{ steps.build_status.outcome }}
        state: ${{ steps.build_status.outcome }}

    - name: Security Check (Dependabot + Trivy)
      id: security_check
      # env:
      #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
      shell: bash
      run: |
        echo "🔍 Running Trivy scan..."
        trivy image \
          --scanners vuln \
          --severity HIGH,CRITICAL,MEDIUM \
          --pkg-types os \
          --exit-code 1 \
          --format table \
          ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:$appVersion
        TRIVY_RESULT=$?

        if [ "$TRIVY_RESULT" -ne 0 ]; then
          echo "❌ Trivy found vulnerabilities (HIGH/CRITICAL/MEDIUM)"
          exit 1
        fi

        echo "✅ Trivy scan passed without blocking issues."

    - name: Update scan status
      if: always()  # Even if previous step fails, this should run.
      uses: nihu-ci/usable-workflow/.github/actions@main
      with:
        context: SCANS
        sha: ${{ github.sha }}
        description: ${{ steps.security_check.outcome }}
        state: ${{ steps.security_check.outcome }}    

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: push image
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${acc_id}.dkr.ecr.us-east-1.amazonaws.com
        docker push ${acc_id}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:$appVersion